force-app/main/default/objects/Error_Logger__c/Error_Logger__c.object-meta.xml
<CustomObject>
    <description>Error logging object that records all failed processes in the system, capturing the context, exception message, and relevant payload data for debugging and operational monitoring purposes.</description>
    <label>Error Logger</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Error Logger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Logger__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Name of the class, method, or process where the error occurred</description>
    <inlineHelpText>Name of the class, method, or process where the error occurred</inlineHelpText>
    <label>Context</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <description>Categorization of errors</description>
    <inlineHelpText>Categorization of errors</inlineHelpText>
    <label>Error Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Error_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Detailed exception message</description>
    <inlineHelpText>Detailed exception message</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Serialized data or payload associated with the failed operation</description>
    <inlineHelpText>Serialized data or payload associated with the failed operation</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Error_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>API</fullName>
        <default>true</default>
        <label>API</label>
    </customValue>
    <customValue>
        <fullName>Batch</fullName>
    </customValue>
    <customValue>
        <fullName>Trigger</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Flow</fullName>
    </customValue>
    <description>Categorize errors type in the system</description>
    <masterLabel>Error Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ErrorLoggerTest.cls
@isTest
public class ErrorLoggerTest {
    public virtual class TestException extends Exception {}

    @isTest
    static void testLogExceptionWithPayload() {
        String context = 'ErrorLoggerTest.testLogExceptionWithPayload';
        String payload = JSON.serialize(TestUtils.buildCasePayload('Test Subject', 'Test Description'));
        TestException testFailure = new TestException('Simulated exception');

        Test.startTest();
        ErrorLogger.logException(testFailure, ApexConstants.ERROR_TYPE_API, context, payload);
        Test.stopTest();

        List<Error_Logger__c> logs = [
            SELECT Context__c, Message__c, Payload__c, Error_Type__c
            FROM Error_Logger__c
            WHERE Context__c = :context
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        Assert.areEqual(1, logs.size(), 'Expected one log record to be created');
        Assert.areEqual(testFailure.getMessage(), logs[0].Message__c, 'Message should match exception the value ' + testFailure.getMessage());
        Assert.areEqual(context, logs[0].Context__c, 'Context should match the value ' + context);
        Assert.areEqual(ApexConstants.ERROR_TYPE_API, logs[0].Error_Type__c, 'Context should match the value ' + ApexConstants.ERROR_TYPE_API);
        Assert.areEqual(payload, logs[0].Payload__c, 'Payload should match provided string value of ' + payload);
    }

    @isTest
    static void testLogExceptionWithoutPayload() {
        String context = 'ErrorLoggerTest.testLogExceptionWithoutPayload';
        TestException testFailure = new TestException('Simulated exception');

        Test.startTest();
        ErrorLogger.logException(testFailure, ApexConstants.ERROR_TYPE_APEX_TRIGGER, context);
        Test.stopTest();

        List<Error_Logger__c> logs = [
            SELECT Context__c, Message__c, Payload__c, Error_Type__c
            FROM Error_Logger__c
            WHERE Context__c = :context
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        Assert.areEqual(1, logs.size(), 'Expected one log record to be created');
        Assert.areEqual(
            testFailure.getMessage(),
            logs[0].Message__c,
            'Message should match exception the value ' + testFailure.getMessage()
        );
        Assert.areEqual(context, logs[0].Context__c, 'Context should match the value ' + context);
        Assert.areEqual(
            ApexConstants.ERROR_TYPE_APEX_TRIGGER,
            logs[0].Error_Type__c,
            'Context should match the value ' + ApexConstants.ERROR_TYPE_APEX_TRIGGER
        );
        Assert.areEqual(null, logs[0].Payload__c, 'Payload should match provided string value of null');
    }

    @isTest
    static void testLogExceptionNegative() {

        Test.startTest();
        ErrorLogger.logException(null, null, null);
        Test.stopTest();

        List<Error_Logger__c> logs = [
            SELECT Context__c, Message__c, Payload__c, Error_Type__c
            FROM Error_Logger__c
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        Assert.areEqual(0, logs.size(), 'Expected zero logs record to be created');
    }
}