force-app/main/default/objects/Error_Logger__c/Error_Logger__c.object-meta.xml
<CustomObject>
    <description>Error logging object that records all failed processes in the system, capturing the context, exception message, and relevant payload data for debugging and operational monitoring purposes.</description>
    <label>Error Logger</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Error Logger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Logger__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Name of the class, method, or process where the error occurred</description>
    <inlineHelpText>Name of the class, method, or process where the error occurred</inlineHelpText>
    <label>Context</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <description>Categorization of errors</description>
    <inlineHelpText>Categorization of errors</inlineHelpText>
    <label>Error Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Error_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Detailed exception message</description>
    <inlineHelpText>Detailed exception message</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Serialized data or payload associated with the failed operation</description>
    <inlineHelpText>Serialized data or payload associated with the failed operation</inlineHelpText>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Error_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>API</fullName>
        <default>true</default>
        <label>API</label>
    </customValue>
    <customValue>
        <fullName>Batch</fullName>
    </customValue>
    <customValue>
        <fullName>Trigger</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Flow</fullName>
    </customValue>
    <description>Categorize errors type in the system</description>
    <masterLabel>Error Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ErrorLogger.cls
/**
 * ErrorLogger class that current creates Error_Logger__c records so that these issues and be logged and addressed in Salesforce.
 * 
 * Currently does not handle bulification but this is something to be built out in the future.
 */
public without sharing class ErrorLogger {

    public static void logException(Exception exceptionObject, String errorType, String context) {
        logException(exceptionObject, errorType, context, null);
    }

    public static void logException(Exception exceptionObject, String errorType, String context, String payload) {
        try {
            Error_Logger__c log = new Error_Logger__c(
                Context__c = context,
                Message__c = exceptionObject.getMessage(),
                Error_Type__c = errorType,
                Payload__c = payload
            );
            insert log;
        } catch (Exception ex) {
            // Fallback if logging fails
            System.debug('Logging failed: ' + ex.getMessage());
        }
    }
}